#! /usr/bin/env python
"""Rectangle compression workflow

Requires the following ``SConscript(..., exports={})``

* ``env`` - The SCons construction environment with the following required keys

  * ``modsim_package_abspath`` - String absolute path to the project package
  * ``solve_cpus`` - Number of cpus to use in Abaqus solve task
  * ``datacheck_alias`` - String for the alias collecting the datacheck workflow targets
  * ``regression_alias`` - String for the alias collecting the regression workflow targets
  * ``abaqus`` - String path for the Abaqus executable

* ``simulation_variables`` - The current simulation parameter set
"""
import pathlib


# Inherit the parent construction environment
Import("env", "simulation_variables", "workflow_name")

# Set project-wide paths with os-agnostic path separators
modsim_package_abspath = env["modsim_package_abspath"]

# Collect the target nodes to build concise target alias(es)
artifacts = []
datacheck = []
images = []

# SolverPrep
abaqus_source_list = [
    modsim_package_abspath / "rectangle_compression.inp.in",
    modsim_package_abspath / "assembly.inp",
    modsim_package_abspath / "boundary.inp",
    modsim_package_abspath / "field_output.inp",
    modsim_package_abspath / "materials.inp",
    modsim_package_abspath / "parts.inp",
    modsim_package_abspath / "history_output.inp"
]
abaqus_source_list = [pathlib.Path(source_file) for source_file in abaqus_source_list]
artifacts.extend(env.CopySubstfile(
    abaqus_source_list,
    substitution_dictionary=env.SubstitutionSyntax(simulation_variables)
))

solve_source_list = [source_file.name.rstrip(".in") for source_file in abaqus_source_list]
solve_source_list.append("rectangle_mesh.inp")

# Part images
images.extend(env.AbaqusJournal(
    target=["rectangle_compression.png"],
    source=[modsim_package_abspath / "export_abaqus_image.py"] + solve_source_list,
    journal_options="--input-file ${SOURCES[1].abspath} --output-file ${TARGET.file} "
                    "--model-name ${model} --part-name ${model}",
    model="rectangle"
))

# Abaqus Solve
datacheck_name = "rectangle_compression_DATACHECK"
datacheck_suffixes = ("023", "mdl", "sim", "stt")
abaqus_options="-double both"
datacheck.extend(env.AbaqusSolver(
    target=[f"{datacheck_name}.{suffix}" for suffix in datacheck_suffixes],
    source=solve_source_list,
    job_name=datacheck_name,
    abaqus_options=f"{abaqus_options} -datacheck"
))

artifacts.extend(env.AbaqusSolver(
    target=["rectangle_compression.sta"],
    source=solve_source_list,
    job_name="rectangle_compression",
    abaqus_options="${global_abaqus_options} -cpus $(${solve_cpus}$)",
    global_abaqus_options=abaqus_options,
    solve_cpus=env["solve_cpus"]
))

# Abaqus Extract
extract_source_list = ["rectangle_compression.odb"]
artifacts.extend(env.AbaqusExtract(
    target=["rectangle_compression.h5"],
    source=extract_source_list
))

# Collector alias based on build directory name
env.Alias(env["regression_alias"], datacheck)
env.Alias(env["datacheck_alias"], datacheck)
env.Alias(f"{workflow_name}_datacheck", datacheck)
env.Alias("images", images)

if not env["ABAQUS_PROGRAM"]:
    print(f"Program 'abaqus' was not found in construction environment. Ignoring '{workflow_name}' target(s)")
    Ignore([".", workflow_name], datacheck)

Return("artifacts")
