schema_version: 1

context:
  name: waves
  version: ${{ env.get("VERSION", default="0.0.0") }}
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: ..
  lfs: true

build:
  number: 0
  noarch: python
  script:
    env:
      SETUPTOOLS_SCM_PRETEND_VERSION: ${{ version }}
    content:
      - if: unix
        then: scons install --prefix=${PREFIX}
      - if: win
        then: scons install --prefix=%PREFIX%
  python:
    entry_points:
      - odb_extract = waves._abaqus.odb_extract:main
      - waves = waves._main:main

requirements:
  host:
    - python
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pip
    - python-build
    - pyyaml
    - salib >=1.4.6
    - scipy >=1.7
    - scons >=4.6
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-book-theme
    - sphinx-copybutton >=0.5.1
    - sphinx-design
    - sphinxcontrib-bibtex
    - xarray >=2024.10.0
  run:
    - python >=${{ python_min }}
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1.4.6
    - scipy >=1.7
    - scons >=4
    - xarray >=2024.10.0

tests:
  - python:
      imports:
        - waves
      pip_check: true
  - script:
      - if: unix
        then:
          - system_test_directory=$PWD
          - cd $SP_DIR/$PKG_NAME
          - pytest -vvv -n 4 -m "not require_third_party" --system-test-dir=${system_test_directory}
      - if: win
        then:
          - set system_test_directory=%CD%
          - cd %SP_DIR%\%PKG_NAME%
          - pytest -vvv -n 4 -m "not require_third_party" --system-test-dir=%system_test_directory%
      - requirements:
        run:
          - python
          - pip
          - pytest >=6
          - pytest-xdist
          - sphinx >=7.1
          - sphinx-argparse
          - sphinx-book-theme
          - sphinxcontrib-bibtex

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Computational science and engineering parameteric study workflows
  description: |
    WAVES (LANL code C23004) is a computational science and engineering workflow tool that integrates parametric studies
    with traditional software build systems.
  homepage: https://github.com/lanl-aea/waves
  repository: https://github.com/lanl-aea/waves
  documentation: https://lanl-aea.github.io/waves/index.html
