#! /usr/bin/env python
import os
import pathlib

import waves


# Write an example custom builder on the WAVES builder factory template
def solver_builder_factory(
    environment: str = "",
    action_prefix: str = "cd ${TARGET.dir.abspath} &&",
    program: str = "solver",
    program_required: str = "",
    program_options: str = "",
    subcommand: str = "implicit",
    subcommand_required: str = "--input-file ${SOURCES[0].abspath} --output-file=${TARGETS[0].abspath}",
    subcommand_options: str = "",
    action_suffix: str = "> ${TARGETS[-1].abspath} 2>&1",
    emitter=waves.scons_extensions.first_target_emitter,
    **kwargs
) -> Builder:
    """
    :return: Solver journal builder
    """  # noqa: E501
    builder = waves.scons_extensions.first_target_builder_factory(
        environment=environment,
        action_prefix=action_prefix,
        program=program,
        program_required=program_required,
        program_options=program_options,
        subcommand=subcommand,
        subcommand_required=subcommand_required,
        subcommand_options=subcommand_options,
        action_suffix=action_suffix,
        emitter=emitter,
        **kwargs
    )
    return builder


AddOption(
    "--build-dir",
    dest="variant_dir_base",
    default="build",
    nargs=1,
    type="string",
    action="store",
    metavar="DIR",
    help="SCons build (variant) root directory. Relative or absolute path. (default: '%default')"
)
AddOption(
    "--solve-cpus",
    dest="solve_cpus",
    default=1,
    nargs=1,
    type="int",
    action="store",
    metavar="N",
    help="Run the solver task using N CPUs. (default: '%default')"
)

env = Environment(
    ENV=os.environ.copy(),
    variant_dir_base=GetOption("variant_dir_base"),
    solve_cpus=GetOption("solve_cpus"),
)
env.AddMethod(waves.scons_extensions.project_help_message, "ProjectHelp")
env.AddMethod(waves.scons_extensions.add_program, "AddProgram")

# Conditionally print failed task *.stdout files
waves.scons_extensions.print_build_failures()

# Empty defaults list to avoid building all simulation targets by default
env.Default()

# Add project builders and scanners
solver_executable = pathlib.Path("solver").resolve()
env["solver"] = env.AddProgram([solver_executable])
env.Append(BUILDERS={
    "Solver": solver_builder_factory(subcommand_options="$(--solve-cpus=${solve_cpus}$)")
})

# Build path object for extension and re-use
variant_dir_base = pathlib.Path(env["variant_dir_base"])

# Add simulation targets
workflow_configurations = [
    "implicit_workflow"
]
for workflow in workflow_configurations:
    build_dir = variant_dir_base / workflow
    SConscript(workflow, variant_dir=build_dir, exports="env", duplicate=False)

# Print project local help
env.ProjectHelp()
