stages:
  - test

include: ".pipeline-common.yml"

before_script:
  # Common job variables
  - conda_installation="${HOME}/anaconda3"
  - conda_environments="${conda_installation}/envs"
  - prefix=$(mktemp --directory --tmpdir=${conda_environments} waves-dev-XXXXXX)
  - echo ${prefix} > prefix.txt
  - prefix_basename="${prefix##*/}"
  - conda_pkgs_dirs="${conda_installation}/pkgs-${prefix_basename}"
  - echo ${conda_pkgs_dirs} > conda_pkgs_dirs.txt
  - conda_artifacts_directory="conda-bld"
  - echo ${conda_installation}
  - echo ${conda_environments}
  - echo ${prefix}
  - echo ${prefix_basename}
  - echo ${conda_pkgs_dirs}
  - echo ${conda_artifacts_directory}
  - if [[ ! -d ${conda_installation} ]]; then exit 1; fi
  - if [[ ! -d ${conda_environments} ]]; then exit 1; fi
  - if [[ -z ${prefix} ]]; then exit 1; fi
  - if [[ -z ${conda_artifacts_directory} ]]; then exit 1; fi
  # Environment creation
  - export CONDA_PKGS_DIRS="${conda_pkgs_dirs}"
  - source ${conda_installation}/etc/profile.d/conda.sh
  - conda info
  - conda env create --prefix ${prefix} --file environment.yml --yes
  - conda activate ${prefix}
  # Common job variables
  - croot=${CONDA_PREFIX}/${conda_artifacts_directory}
  - echo ${croot}
  - if [[ -z ${croot} ]]; then exit 1; fi

after_script:
  - prefix=$(cat prefix.txt)
  - conda_pkgs_dirs=$(cat conda_pkgs_dirs.txt)
  - echo ${prefix}
  - if [[ -z ${prefix} ]]; then exit 1; fi
  - rm -r ${prefix} || true
  - rm -r ${conda_pkgs_dirs} || true

mac-fast-test:
  extends:
    - .fast-test-no-third-party
  stage: test
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - macos
    - pn2301275

mac-conda-build-external:
  extends:
    - .conda-build
  stage: test
  variables:
    recipe_directory: "recipe"
  rules:
    - if: $PARENT_CI_PIPELINE_SOURCE == "schedule"
    - if: $PARENT_CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - macos
    - pn2301275
