#! /usr/bin/env python

# Inherit the parent construction environment
Import("env")

target = env.Command(
    target=["flake8.txt"],
    source=["flake8"],
    action=["flake8 --tee --output-file=${TARGET.abspath}"]
)
env.AlwaysBuild(target)
env.Alias("flake8", target)
