#! /usr/bin/env python

# Inherit the parent construction environment
Import("env")

pyproject = env.FindFile("pyproject.toml", "#")

target = env.Command(
    target=["flake8.txt"],
    source=[".flake8"],
    action=["flake8 . $$(python find_shebang.py .) --jobs=4 --tee --output-file=${TARGET.abspath}"],
)
env.AlwaysBuild(target)
env.Alias("flake8", target)

target = env.Command(
    target=["black-check.txt"],
    source=[pyproject],
    action=["black . $$(python find_shebang.py .) --check --verbose ${action_suffix}"],
    action_suffix=env["tee_suffix"],
)
env.AlwaysBuild(target)
env.Alias("black-check", target)

# TODO: Remove custom python script if/when black supports magic file type searches
# https://github.com/psf/black/issues/491
target = env.Command(
    target=["black-format.txt"],
    source=[pyproject],
    action=["black . $$(python find_shebang.py .) ${action_suffix}"],
    action_suffix=env["tee_suffix"],
)
env.AlwaysBuild(target)
env.Alias("black-format", target)
