#! /usr/bin/env python

# Inherit the parent construction environment
Import("env")

target = env.Command(
    target=["flake8.txt"],
    source=["style"],
    action=["flake8 --jobs=4 --tee --output-file=${TARGET.abspath}"],
)
env.AlwaysBuild(target)
env.Alias("flake8", target)

target = env.Command(
    target=["black.txt"],
    source=["style"],
    action=["black SConstruct docs/SConscript pytest style mypy waves/ --check > ${TARGET.abspath} 2>&1"],
)
env.AlwaysBuild(target)
env.Alias("black", target)
