#! /usr/bin/env python

# Only required when WAVES is not installed as a package, e.g. for local testing in WAVES repository.
try:
    import waves
except ModuleNotFoundError:
    sys.path.insert(0, str(pathlib.Path('..').resolve()))
    import waves

# Inherit the parent construction environment
Import(['env', 'project_variables'])

# Set empty alias return list
alias_list = []

# Perform variable substitution on Sphinx configuration file
env.Substfile(
    "conf.py.in",
    SUBST_DICT=waves.builders.substitution_syntax(project_variables))

# Explicit Sphinx documentation dependency list
documentation_file_list = [
    'conf.py',
    'README.txt',  # Copied from README.rst to docs build directory by root SConscript
    'environment.txt',  # Copied from environment.txt to docs build directory by root SConscript
    'api.rst',
    'cli.rst',
    'build.txt',
    'changelog.rst',
    'contribution.txt',
    'dependencies.txt',
    'devops.rst',
    'documentation.txt',
    'glossary.rst',
    'index.rst',
    'mesh_convergence.rst',
    'nominal.rst',
    'project_brief.txt',
    'references.bib',
    'release_philosophy.rst',
    'targets.txt',
    'user.rst',
    'waves_logo_brandmark_smaller.png',
    'zreferences.rst',
    '_static/custom.css'
]

# TODO: os agnostic pathsep for the html directory
# https://re-git.lanl.gov/aea/python-projects/waves/-/issues/4
sphinx_options = '-W'
html = env.Command(
    target=[Dir('html')],
    source=documentation_file_list,
    action=f"{env['sphinx_build']} ${{sphinx_options}} -b html ${{TARGET.dir.abspath}} ${{TARGET.dir.abspath}}/html",
    sphinx_options=sphinx_options)
env.Clean(html, Dir('html'))
env.AlwaysBuild(html)
alias_list.extend(env.Alias('html', html))

# Collector alias to build all documentation
alias_list.extend(env.Alias('documentation', html))

if not env['unconditional_build'] and not env['sphinx_build']:
    print(f"Program 'sphinx-build' was not found in construction environment. Ignoring Sphinx target(s)")
    Ignore(['.', 'html', 'html'], html)
else:
    env.Default(html)

# Return the alias list to SConstruct for help message output
Return('alias_list')
