#! /usr/bin/env python

Import("env", "envCubit")

# Geometry
envCubit.PythonScript(
    target=["cube_geometry.cub"],
    source=["cube_geometry.py"],
    subcommand_options="",
)

# Partition
envCubit.PythonScript(
    target=["cube_partition.cub"],
    source=["cube_partition.py", "cube_geometry.cub"],
    subcommand_options="",
)

# Mesh
envCubit.PythonScript(
    target=[f"cube_mesh.g", "cube_mesh.cub"],
    source=["cube_mesh.py", "cube_partition.cub"],
    subcommand_options="--element-type ${element_type} --solver ${solver}",
    element_type="HEX",
    solver="sierra",
)

# Solve
stretch_hex_targets = env.Truchas(
    target=[
        "cube_compression/cube_compression.log",
        "cube_compression/cube_compression.h5",
    ],
    source=["cube_compression.inp", "cube_mesh.g"],
)
env.Alias("cube_compression.inp", stretch_hex_targets)

if not env["TRUCHAS_PROGRAM"]:
    print(f"Program 'truchas' was not found in construction environment. Ignoring simulation target(s)")
    Ignore([".", "cube_compression.inp"], stretch_hex_targets)
