#! /usr/bin/env python

import pathlib

# Inherit the parent construction environment
Import('env')

# Set project-wide paths with os-agnostic path separators
project_dir = pathlib.Path(env['project_dir'])
abaqus_source_dir = env['abaqus_source_dir']
abaqus_source_abspath = project_dir / abaqus_source_dir

# Simulation variables
model = "single_element"

# Geometry
journal_file = f"{model}_geometry"
journal_options = ""
geometry = env.AbaqusJournal(
    target=[f"{journal_file}.cae"],
    source=[f"{abaqus_source_abspath / journal_file}.py"],
    journal_options=journal_options)

# Collector alias based on parent directory name
parent_directory = pathlib.Path('.').parent.name
workflow = geometry
env.Alias(parent_directory, workflow)

if not env['abaqus'] and env['conditional_ignore']:
    print(f"Program 'abaqus' was not found in construction environment. Skipping Abaqus target(s)")
    Ignore(['.', parent_directory], workflow)
