#! /usr/bin/env python

# Inherit the parent construction environment
Import('env')

journal_file = "single_element_geometry"
journal_options = ""

tutorial_01_geometry = env.AbaqusJournal(
    target=[f"{journal_file}.cae", f"{journal_file}.jnl", f"{journal_file}.log"],
    source=[f"{env['PROJECT_DIR']}/{env['ABAQUS_SOURCE_DIR']}/{journal_file}.py"],
    journal_options=journal_options)
