#! /usr/bin/env python

# Inherit the parent construction environment
Import('env')

# Limit list of source files to allow Conda build test to avoid copying waves source code and test off the installed
# waves package
waves_source_list = [
    '../pyproject.toml',
]

pytest_node = env.Command(
    chdir='waves',
    target='test_results.xml',
    source=waves_source_list,
    action='PYTHONDONTWRITEBYTECODE=1 pytest')
alias_list = env.Alias('pytest', pytest_node)
# Always run pytests in place of a complete source list
env.AlwaysBuild(pytest_node)

# Return the alias list to SConstruct for help message output
Return('alias_list')
