#! /usr/bin/env python

import pathlib

# Inherit the parent construction environment
Import('env')

# Set project-wide paths with os-agnostic path separators
project_dir = pathlib.Path(env['PROJECT_DIR'])
abaqus_source_dir = env['ABAQUS_SOURCE_DIR']
abaqus_source_abspath = project_dir / abaqus_source_dir

# Simulation variables
model = "single_element"

# Geometry
journal_file = f"{model}_geometry"
journal_options = ""
geometry = env.AbaqusJournal(
    target=[f"{journal_file}.cae"],
    source=[f"{abaqus_source_abspath / journal_file}.py"],
    journal_options=journal_options)

# Partition
journal_file = f"{model}_partition"
journal_options = ""
partition = env.AbaqusJournal(
    target=[f"{journal_file}.cae"],
    source=[f"{abaqus_source_abspath / journal_file}.py", f"{model}_geometry.cae"],
    journal_options=journal_options)

# Mesh
journal_file = f"{model}_mesh"
journal_options = ""
mesh = env.AbaqusJournal(
    target=[f"{journal_file}.cae", f"{journal_file}.inp"],
    source=[f"{abaqus_source_abspath / journal_file}.py", f"{model}_partition.cae"],
    journal_options=journal_options)

# SolverPrep
abaqus_source_list = [
    f"#/{abaqus_source_dir}/{model}_compression.inp",
    f"#/{abaqus_source_dir}/amplitudes.inp",
    f"#/{abaqus_source_dir}/assembly.inp",
    f"#/{abaqus_source_dir}/boundary.inp",
    f"#/{abaqus_source_dir}/field_output.inp",
    f"#/{abaqus_source_dir}/materials.inp",
    f"#/{abaqus_source_dir}/parts.inp",
    f"#/{abaqus_source_dir}/history_output.inp"
]
abaqus_source_list = [pathlib.Path(source_file) for source_file in abaqus_source_list]
# TODO: Write copy/substitute function that accepts a list of strings or pathlib.Path objects
# https://re-git.lanl.gov/kbrindley/scons-simulation/-/issues/28
solverprep = list()
for source_file in abaqus_source_list:
    # Copy all files in list to build directory without changing extension
    solverprep.append(
        Command(
            target=source_file.name,
            source=str(source_file),
            action=Copy('${TARGET}', '${SOURCE}')))
    # Run substitution dictionary on anything with *.in template extension
    if source_file.suffix == '.in':
        solverprep.append(Substfile(source_file.name))

# Abaqus Solve
abaqus_build_list = [source_file.name.rstrip('.in') for source_file in abaqus_source_list]
# TODO: Add a datacheck simulation
# https://re-git.lanl.gov/kbrindley/scons-simulation/-/issues/30
job_name = f'{model}_compression'
abaqus_options = ''
solve_source_list = abaqus_build_list + [f"{journal_file}.inp"]
solve = env.AbaqusSolver(
    target=[],
    source=solve_source_list,
    job_name=job_name,
    abaqus_options=abaqus_options)

# Collector alias
env.Alias('${SOURCE_DIR.srcdir}', [geometry, partition, mesh, solve] + solverprep)
