#! /usr/bin/env python

import os
import sys
import pathlib

import waves

# Comments used in tutorial code snippets: marker-1

# Accept command line options with fall back default values
AddOption(
    "--build-dir",
    dest="variant_dir_base",
    default="build",
    nargs=1,
    type="string",
    action="store",
    metavar="DIR",
    help="SCons build (variant) root directory. Relative or absolute path. (default: '%default')"
)
AddOption(
    "--unconditional-build",
    dest="unconditional_build",
    default=False,
    action="store_true",
    help="Boolean flag to force building of conditionally ignored targets, e.g. if the target's action program is missing" \
            " and it would normally be ignored. (default: '%default')"
)

# Comments used in tutorial code snippets: marker-2

# Inherit user's full environment and set project variables
env = Environment(ENV=os.environ.copy(),
                  variant_dir_base=GetOption("variant_dir_base"),
                  unconditional_build=GetOption("unconditional_build"))

# Comments used in tutorial code snippets: marker-3

# Find required programs for conditional target ignoring and absolute path for use in target actions
env['abaqus'] = waves.builders.find_program(['abq2021', 'abq2020'], env)

# Comments used in tutorial code snippets: marker-4

# Set project internal variables and variable substitution dictionaries
project_name = 'WAVES-EABM-TUTORIAL'
version = '0.1.0'
project_dir = pathlib.Path(Dir(".").abspath)
abaqus_source_dir = "eabm_package/abaqus"
project_variables = {
    'project_name': project_name,
    'project_dir': str(project_dir),
    'version': version,
    'abaqus_source_abspath': str(project_dir / abaqus_source_dir)
}
for key, value in project_variables.items():
    env[key] = value

# Comments used in tutorial code snippets: marker-5

# Build path object for extension and re-use
variant_dir_base = pathlib.Path(env['variant_dir_base'])

# Add custom builders
env.Append(BUILDERS={'AbaqusJournal': waves.builders.abaqus_journal(abaqus_program=env['abaqus'])})

# Comments used in tutorial code snippets: marker-6

# Add simulation targets
eabm_simulation_directories = [
    'tutorial_01_geometry',
    'tutorial_02_partition_mesh',
    'tutorial_03_solverprep'
]
for source_dir in eabm_simulation_directories:
    build_dir = variant_dir_base / source_dir
    SConscript(dirs=source_dir, variant_dir=build_dir, exports='env', duplicate=False)

# Comments used in tutorial code snippets: marker-7

# Add default target list to help message
env.Default()  # Empty defaults list to avoid building all simulation targets by default
default_targets_help = "\nDefault Targets:\n"
for target in DEFAULT_TARGETS:
    default_targets_help += f"    {str(target)}\n"
Help(default_targets_help, append=True)

# Comments used in tutorial code snippets: marker-8

# Add aliases to help message so users know what build target options are available
# This must come *after* all expected Alias definitions and SConscript files.
try:
    # Recover from SCons configuration
    from SCons.Node.Alias import default_ans
    alias_list = default_ans
except ImportError:
    # Fall back to manually constructed alias list(s)
    alias_list = eabm_simulation_directories
alias_help = "\nTarget Aliases:\n"
for alias in alias_list:
    alias_help += f"    {alias}\n"
Help(alias_help)

# Comments used in tutorial code snippets: marker-9
