#! /usr/bin/env python

import os
import pathlib
import waves

# Inherit user's full environment
env = Environment(ENV=os.environ.copy())

# Empty defaults list to avoid building all simulation targets by default
env.Default()

# Set project-wide paths with os-agnostic path separators
project_dir = pathlib.Path(Dir('.').abspath)
abaqus_source_dir = 'eabm_package/abaqus'
variant_dir_base = pathlib.Path('build_waves_quickstart')

# Make the EABM package importable for Python and Abaqus Python environments
env.PrependENVPath("PYTHONPATH", str(project_dir))

# Separate target output from source files
VariantDir(variant_dir_base.name, '.', duplicate=False)

# Find required programs for conditional target ignoring and absolute path for use in target actions
env['abaqus'] = waves.builders.add_program(["/apps/abaqus/Commands/abq2022", "abq2022"], env)

# Add WAVES builders
env.Append(BUILDERS=
    {'AbaqusJournal': waves.builders.abaqus_journal(program=env['abaqus']),
     'AbaqusSolver': waves.builders.abaqus_solver(program=env['abaqus'])})

# Simulation variables
model = "rectangle"

# Collect the target nodes to build a concise alias for all targets
workflow = []

# Geometry
journal_options = ""
workflow.extend(env.AbaqusJournal(
    target=[str(variant_dir_base / "rectangle_geometry.cae")],
    source=[str(project_dir / abaqus_source_dir / "rectangle_geometry.py")],
    journal_options=journal_options))

# Partition
journal_options = ""
workflow.extend(env.AbaqusJournal(
    target=[str(variant_dir_base / "rectangle_partition.cae")],
    source=[str(project_dir / abaqus_source_dir / "rectangle_partition.py"),
            str(variant_dir_base / "rectangle_geometry.cae")],
    journal_options=journal_options))

# Mesh
journal_options = ""
workflow.extend(env.AbaqusJournal(
    target=[str(variant_dir_base / "rectangle_mesh.inp"),
            str(variant_dir_base / "rectangle_mesh.cae")],
    source=[str(project_dir / abaqus_source_dir / "rectangle_mesh.py"),
            str(variant_dir_base / "rectangle_partition.cae")],
    journal_options=journal_options))

# SolverPrep
abaqus_source_list = [
    project_dir / abaqus_source_dir / "rectangle_compression.inp",
    project_dir / abaqus_source_dir / "assembly.inp",
    project_dir / abaqus_source_dir / "boundary.inp",
    project_dir / abaqus_source_dir / "field_output.inp",
    project_dir / abaqus_source_dir / "materials.inp",
    project_dir / abaqus_source_dir / "parts.inp",
    project_dir / abaqus_source_dir / "history_output.inp"
]
workflow.extend(waves.builders.copy_substitute(abaqus_source_list, build_subdirectory=str(variant_dir_base)))

# Abaqus Solve
abaqus_options = '-double both'
solve_source_list = [str(variant_dir_base / source_file.name) for source_file in abaqus_source_list]
solve_source_list.append(str(variant_dir_base / "rectangle_mesh.inp"))

workflow.extend(env.AbaqusSolver(
    target=[str(variant_dir_base / "rectangle_compression.sta")],
    source=solve_source_list,
    job_name="rectangle_compression",
    abaqus_options=abaqus_options))

# Collector alias named after the model simulation
env.Alias('rectangle', workflow)

if not env['abaqus']:
    print("Program 'abaqus' was not found in construction environment. Ignoring 'rectangle' target(s)")
    Ignore(['.', 'rectangle'], workflow)
