#! /usr/bin/env python
#
# Inherit the parent construction environment
Import('documentation_source_dir')

readme_target = Command(
    target=f"{documentation_source_dir}/README.txt",
    source="README.rst",
    action=Copy("$TARGET", "$SOURCE"))

# Add this target to the defaults list
Default(readme_target)
