#! /usr/bin/env python
Import("env", "set_name", "parameters", "simulation_constants")

env.Command(
    target=[f"cat_{set_name}.txt"],
    source=["one.txt", "two.txt"],
    action=[
        "echo workflow '${workflow}' > ${TARGET.abspath}",
        "cat ${cat_options} ${SOURCES.abspath} >> ${TARGET.abspath}",
        "tail ${tail_options} ${TARGET.abspath}"
    ],
    **parameters,
    **simulation_constants
)
