#! /usr/bin/env python
Import("env", "set_name", "parameters")

env.Command(
    target=[f"echo_{set_name}.txt"],
    source=["one.txt", "two.txt"],
    action=[
        "echo workflow '${workflow}' > ${TARGET.abspath}",
        "echo ${SOURCES.abspath} >> ${TARGET.abspath}",
    ],
    **parameters,
)
