#! /usr/bin/env python

# Inherit the parent construction environment
Import('env')

# Simulation variables
model = "single_element"

# Geometry
journal_file = f"{model}_geometry"
journal_options = ""
geometry = env.AbaqusJournal(
    target=[f"{journal_file}.cae", f"{journal_file}.jnl", f"{journal_file}.log"],
    source=[f"{env['PROJECT_DIR']}/{env['ABAQUS_SOURCE_DIR']}/{journal_file}.py"],
    journal_options=journal_options)

# Partition
journal_file = f"{model}_partition"
journal_options = ""
partition = env.AbaqusJournal(
    target=[f"{journal_file}.cae", f"{journal_file}.jnl", f"{journal_file}.log"],
    source=[f"{env['PROJECT_DIR']}/{env['ABAQUS_SOURCE_DIR']}/{journal_file}.py", f"{model}_geometry.cae"],
    journal_options=journal_options)

# Mesh
journal_file = f"{model}_mesh"
journal_options = ""
mesh = env.AbaqusJournal(
    target=[f"{journal_file}.cae", f"{journal_file}.inp", f"{journal_file}.jnl", f"{journal_file}.log"],
    source=[f"{env['PROJECT_DIR']}/{env['ABAQUS_SOURCE_DIR']}/{journal_file}.py", f"{model}_partition.cae"],
    journal_options=journal_options)

# Collector alias
env.Alias('${SOURCE_DIR.srcdir}', [geometry, partition, mesh])
