#! /usr/bin/env python

import waves


env = Environment()
env.AddMethod(waves.scons_extensions.parameter_study_write, "ParameterStudyWrite")

schema = {"one": [1, 2]}
one_file = waves.parameter_generators.CartesianProduct(
    schema,
    output_file="build/one_file.h5",
)
two_file = waves.parameter_generators.CartesianProduct(
    schema,
    output_file_template="build/two_file@number.h5",
)

env.ParameterStudyWrite(
    one_file,
)
env.ParameterStudyWrite(
    two_file,
)

# Remove the duplicate parameter generator when the write API allows output file name overrides
# https://re-git.lanl.gov/aea/python-projects/waves/-/issues/634
one_file = waves.parameter_generators.CartesianProduct(
    schema,
    output_file="build/one_file.yaml",
)
two_file = waves.parameter_generators.CartesianProduct(
    schema,
    output_file_template="build/two_file@number.yaml",
)

yaml = env.ParameterStudyWrite(
    one_file,
    output_file_type="yaml",
)
yaml = env.ParameterStudyWrite(
    two_file,
    output_file_type="yaml",
)
