#! /usr/bin/env python
#
# Inherit the parent construction environment
Import(["env"])

readme_target = Command(
    target=f"{env['documentation_dir']}/README.txt",
    source="README.rst",
    action=Copy("$TARGET", "$SOURCE"))

Command(
    target=f"{env['documentation_dir']}/environment.txt",
    source="environment.txt",
    action=Copy("$TARGET", "$SOURCE"))

environment_target = env.CondaEnvironment(
    target=["environment.yaml"],
    source=[])
env.AlwaysBuild(environment_target)

# Add this target to the defaults list
Default(readme_target, environment_target)
