#! /usr/bin/env python

# Inherit the parent construction environment
Import(["env"])

environment_target = env.CondaEnvironment(
    target=["environment.yaml"],
    source=[])
env.AlwaysBuild(environment_target)

# Add this target to the defaults list
Default(environment_target)
