Import('env')                                                                                                            
                                                                                                                         
# Geometry                                                                                                               
env.AbaqusJournal(                                                                                                       
    target="rectangle_geometry.cae",
    source="rectangle_geometry.py"
)
                                                                                                                         
# Partition                                                                                                              
env.AbaqusJournal(                                                                                                       
    target="rectangle_partition.cae",
    source=["rectangle_partition.py", "rectangle_geometry.cae"]
)
                                                                                                                         
# Mesh                                                                                                                   
env.AbaqusJournal(                                                                                                       
    target=["rectangle_mesh.inp", "rectangle_mesh.cae"],
    source=["rectangle_mesh.py", "rectangle_partition.cae", "abaqus_journal_utilities.py"]
)
                                                                                                                         
# Abaqus Solve                                                                                                           
target = env.AbaqusSolver(                                                                                               
    target="rectangle_compression.odb",
    source="rectangle_compression.inp",
    job_name="rectangle_compression",
    abaqus_options="-double both"
)
                                                                                                                         
# Collector alias named after the model simulation                                                                       
env.Alias('rectangle', target)
