import waves


Import("env", "study", "subdirectories")

targets = []
targets.extend(
    env.ParameterStudyTask(
        env.TestBuilder,
        target=["@{set_name}target1.txt"],
        source=["source1.txt"],
        study=study,
        subdirectories=subdirectories,
    )
)
targets.extend(
    env.ParameterStudyTask(
        env.TestBuilder,
        target=["@{set_name}target2.txt"],
        source=["@{set_name}target1.txt"],
        study=study,
        subdirectories=subdirectories,
    )
)
