#! /usr/bin/env python

import os
import pathlib

# Add build directory CLI arg
AddOption(
    "--build-dir",
    dest="build_dir",
    default="build",
    nargs=1,
    type="string",
    action="store",
    metavar="DIR",
    help="SCons build (variant) root directory. Relative or absolute path. (default: '%default')"
)

# Inherit user's full environment
env = Environment(
    ENV=os.environ.copy(),
    build_dir=GetOption('build_dir')
)

# Always copy (no sym-links) when duplicating
env.SetOption('duplicate', 'copy')

# Empty defaults list to avoid building all simulation targets by default
env.Default()

# Find required programs for conditional target ignoring and absolute path for use in target actions
conf = env.Configure()
env['abaqus'] = conf.CheckProg('/apps/abaqus/Commands/abq2023')
conf.Finish()
if env['abaqus']:
    env.PrependENVPath("PATH", str(pathlib.Path(env['abaqus']).parent))

# Write project builders for re-use in task definitions
abaqus_journal = Builder(
    action="cd ${TARGET.dir.abspath} && ${abaqus_program} cae -noGui ${SOURCE.abspath} " \
           "${abaqus_options} -- ${journal_options}")

abaqus_solver = Builder(
    action="cd ${TARGET.dir.abspath} && ${abaqus_program} -job ${job_name} -input ${SOURCE.filebase} " \
           "${abaqus_options} -interactive -ask_delete no")

# Add custom builders
env.Append(BUILDERS={
    'AbaqusJournal': abaqus_journal,
    'AbaqusSolver': abaqus_solver
})

# Call SConscript file
SConscript('SConscript', variant_dir=env['build_dir'], exports='env', duplicate=True)
