#! /usr/bin/env python
"""Rectangle compression workflow

Requires the following ``SConscript(..., exports={})``

* ``env`` - The SCons construction environment with the following required keys

  * ``abaqus_source_abspath`` - String absolute path to the project's Abaqus journal files
  * ``unconditional_build`` - Boolean flag to force building of conditionally ignored targets
  * ``abaqus`` - String path for the Abaqus executable
"""

import pathlib

# Inherit the parent construction environment
Import("env")

# Set project-wide paths with os-agnostic path separators
abaqus_source_abspath = env["abaqus_source_abspath"]

# Simulation variables
build_directory = pathlib.Path(Dir(".").abspath)
workflow_name = build_directory.name

# Comment used in tutorial code snippets: marker-1

# Collect the target nodes to build a concise alias for all targets
workflow = []

# Geometry
journal_file = "rectangle_geometry"
journal_options = ""
workflow.extend(
    env.AbaqusJournal(
        target=[f"{journal_file}.cae", f"{journal_file}.jnl"],
        source=[f"{abaqus_source_abspath / journal_file}.py"],
        subcommand_options=journal_options,
    )
)

# Comment used in tutorial code snippets: marker-2

# Partition
journal_file = "rectangle_partition"
journal_options = ""
workflow.extend(
    env.AbaqusJournal(
        target=[f"{journal_file}.cae", f"{journal_file}.jnl"],
        source=[f"{abaqus_source_abspath / journal_file}.py", "rectangle_geometry.cae"],
        subcommand_options=journal_options,
    )
)

# Mesh
journal_file = "rectangle_mesh"
journal_options = ""
workflow.extend(
    env.AbaqusJournal(
        target=[f"{journal_file}.inp", f"{journal_file}.cae", f"{journal_file}.jnl"],
        source=[f"{abaqus_source_abspath / journal_file}.py", "rectangle_partition.cae"],
        subcommand_options=journal_options,
    )
)

# Comment used in tutorial code snippets: marker-3

# SolverPrep
abaqus_source_list = [
    abaqus_source_abspath / "rectangle_compression.inp",
    abaqus_source_abspath / "assembly.inp",
    abaqus_source_abspath / "boundary.inp",
    abaqus_source_abspath / "field_output.inp",
    abaqus_source_abspath / "materials.inp",
    abaqus_source_abspath / "parts.inp",
    abaqus_source_abspath / "history_output.inp",
]
abaqus_source_list = [pathlib.Path(source_file) for source_file in abaqus_source_list]
workflow.extend(env.CopySubstfile(abaqus_source_list))

# Comment used in tutorial code snippets: marker-4

# Collector alias based on parent directory name
env.Alias(workflow_name, workflow)

if not env["unconditional_build"] and not env["ABAQUS_PROGRAM"]:
    print(f"Program 'abaqus' was not found in construction environment. Ignoring '{workflow_name}' target(s)")
    Ignore([".", workflow_name], workflow)
