#! /usr/bin/env python
"""Rectangle compression workflow

Requires the following ``SConscript(..., exports=[])``

* ``env`` - The SCons construction environment with the following required keys

  * ``test_source_abspath`` - String absolute path to the EABM's Python 3 test files
"""

import pathlib

# Inherit the parent construction environment
Import('env')

# Set project-wide paths with os-agnostic path separators
test_source_abspath = pathlib.Path(env["test_source_abspath"])

# Set unit test workflow variables
build_directory = pathlib.Path(Dir('.').abspath)
workflow_name = build_directory.name

# Set test files
test_files = [
    test_source_abspath / "test_post_processing.py"
]

# Unit test target
unittest_command = "pytest --junitxml=${TARGETS[0]} ${SOURCES.abspath}"
target = [f"{workflow_name}_results.xml"]
unittest_node = env.Command(
    target=target,
    source=test_files,
    action=unittest_command
)

env.Alias(workflow_name, unittest_node)
