import os
env = Environment(ENV=os.environ.copy())

Command(target="conf.py",
        source="conf.py.in",
        action=Copy("$TARGET", "$SOURCE"))

documentation_file_list = [
    'changelog.rst',
    'index.rst',
    'project_brief.txt',
    'references.bib',
    'release_philosophy.rst',
    'targets.txt',
    'model_repository_user.rst',
    'build.txt',
    'documentation.txt',
    'zreferences.rst',
    '_static/custom.css'
]

# TODO: Find the sphinx-build program with scons
# TODO: os agnostic pathsep for the html directory
sphinx = Builder(action="sphinx-build -b html ${TARGET.dir.abspath} ${TARGET.dir.abspath}/html")
env.Append(BUILDERS = {'Sphinx': sphinx})
env.Sphinx(target='index.html', source=documentation_file_list)
