package:
  name: waves
  # TODO: Figure out how to use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

about:
  home: https://re-git.lanl.gov/aea/python-projects/waves
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Computational science and engineering parameteric study workflows'
  description: |
    WAVES (LANL code C23004) is a computational science and engineering workflow tool that integrates parametric studies
    with traditional software build systems.
  doc_url: https://aea.re-pages.lanl.gov/python-projects/waves/index.html
  dev_url: https://re-git.lanl.gov/aea/python-projects/waves

source:
  path: '..'

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ VERSION }}
  entry_points:
    - odb_extract = waves._abaqus.odb_extract:main
    - waves = waves._main:main

requirements:
  host:
    - python
    - python-build
    - pip
    - scons >=4.6
    - setuptools >=64
    - setuptools_scm >=8
    - sphinx >=7.1
    - sphinx-argparse
    - sphinx-copybutton >=0.5.1
    - sphinx-book-theme
    - sphinx-design
    - sphinxcontrib-bibtex
  run:
    - python >=3.9
    - h5netcdf
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pyyaml
    - salib >=1
    - scipy >=1.7
    - scons >=4
    - xarray

test:
  requires:
    - calculix
    - ccx2paraview
    - fierro-fe-cpu
    - gmsh
    - h5netcdf
    - h5py
    - matplotlib-base
    - meshio
    # Required to satisfy undocumented SALib dependencies on numpy version for the senstivity study tutorial
    - numpy >=2
    - pandas
    - paraview
    - pip
    - pytest
    - pytest-xdist
    - python-gmsh
    - pyyaml
    # Required to satisfy undocumented SALib dependencies on numpy version for the senstivity study tutorial
    - salib >=1.5.1
    - scipy >=1.7
    - scons
    - seaborn
    - sed
    - setuptools_scm
    - xarray
  imports:
    - waves
