name: Windows build and test on new tags

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          fetch-depth: 0
      - name: MiniConda setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          miniforge-version: latest
      - name: Conda environment
        shell: powershell
        run: conda install boa conda-build conda-verify --yes
      - name: Conda build
        shell: powershell
        run: $env:VERSION=(python -m setuptools_scm); conda mambabuild recipe --channel conda-forge --no-anaconda-upload --output-folder conda-bld
